SET SERVEROUTPUT ON

DECLARE
    
    V_NOME VARCHAR2(50) ;
    V_RM NUMBER(10) := 222333444 ;

    

BEGIN

    SELECT nome  INTO V_NOME FROM ALUNO WHERE RM = V_RM;

    DBMS_OUTPUT.PUT_LINE('O NOME DO ALUNO É: '|| V_NOME);

END;