DROP TABLE ALUNO;


CREATE TABLE ALUNO (
    RM NUMBER(10),
    NOME VARCHAR2(50),
    CONSTRAINT PK_ALUNO PRIMARY KEY(RM)
);

INSERT INTO ALUNO (RM, NOME) VALUES (111222333, 'João');
INSERT INTO ALUNO (RM, NOME) VALUES (222333444, 'Maria');
INSERT INTO ALUNO (RM, NOME) VALUES (333444555, 'José');

COMMIT;
