SET SERVEROUTPUT ON

DECLARE

    V_NUMERO_IMPRESSO NUMBER(10) := 1;

BEGIN

    LOOP
        DBMS_OUTPUT.PUT_LINE(V_NUMERO_IMPRESSO);
        
        V_NUMERO_IMPRESSO := V_NUMERO_IMPRESSO + 1;
    
        EXIT WHEN (V_NUMERO_IMPRESSO > 100000000);
    END LOOP;

END;

