SET SERVEROUTPUT ON

DECLARE
-- 444555666
--DANIELA
    V_NOME VARCHAR2(50) := 'DANIELA';
    V_RM NUMBER(10) := 444555666;


BEGIN
    --COMANDO SQL - DML - INSERT
    
    INSERT INTO ALUNO (RM, NOME)  VALUES ( V_RM, V_NOME );

    DBMS_OUTPUT.PUT_LINE('ALUNO INCLUIDO COM SUCESSO');
    
    COMMIT;

END;



SELECT * FROM ALUNO;